language: node_js
node_js:
- '0.12'
sudo: true
env:
  global:
  - CF_APP=supply-chain-weather
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=Dev-Advocates
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/supply-chain-weather
